#!/usr/bin/env python3
"""Deletes memory videos generated by generate.py after RETENTION_DAYS,
unless the user has marked them as favorite in Immich."""
import os
import sys
import json
import urllib.request
from datetime import date, datetime, timedelta

IMMICH_URL = os.environ.get("IMMICH_URL", "http://localhost:2283")
API_KEY = os.environ["IMMICH_API_KEY"]
STATE_FILE = os.environ.get("STATE_FILE", "/state/generated-assets.log")
RETENTION_DAYS = int(os.environ.get("RETENTION_DAYS", "7"))


def api_get(path):
    req = urllib.request.Request(IMMICH_URL + path, headers={"x-api-key": API_KEY})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def api_delete_asset(asset_id):
    body = json.dumps({"ids": [asset_id]}).encode()
    req = urllib.request.Request(
        IMMICH_URL + "/api/assets",
        data=body,
        method="DELETE",
        headers={"x-api-key": API_KEY, "Content-Type": "application/json"},
    )
    urllib.request.urlopen(req, timeout=30)


def main():
    if not os.path.exists(STATE_FILE):
        print("No state file, nothing to purge.")
        return

    with open(STATE_FILE, encoding="utf-8") as f:
        lines = [l.strip() for l in f if l.strip()]

    cutoff = date.today() - timedelta(days=RETENTION_DAYS)
    kept_lines = []
    for line in lines:
        parts = line.split()
        if len(parts) != 2:
            continue
        day_str, asset_id = parts
        try:
            day = datetime.strptime(day_str, "%Y-%m-%d").date()
        except ValueError:
            continue

        if day > cutoff:
            kept_lines.append(line)
            continue

        try:
            asset = api_get(f"/api/assets/{asset_id}")
        except Exception as e:
            print(f"SKIP (not found / API error) {asset_id}: {e}")
            continue

        if asset.get("isFavorite"):
            print(f"KEEP (favorite) {asset_id} from {day_str}")
            continue

        try:
            api_delete_asset(asset_id)
            print(f"DELETE {asset_id} from {day_str} (not favorite, > {RETENTION_DAYS}d)")
        except Exception as e:
            print(f"ERROR deleting {asset_id}: {e}")
            kept_lines.append(line)

    with open(STATE_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(kept_lines) + ("\n" if kept_lines else ""))


if __name__ == "__main__":
    main()
